#!/usr/bin/env bash

# Fixed pointer geometry for the mapped 1600x900, five-track fixture window.
ROW0_TITLE_CELL_X=355
ROW0_TITLE_CELL_Y=170
ROW1_TITLE_CELL_X=355
ROW1_TITLE_CELL_Y=221
ROW0_RATING_BUTTON_X=1548
ROW0_RATING_BUTTON_Y=170
ROW0_RATING_POPOVER_STAR2_X=1415
ROW0_RATING_POPOVER_STAR2_Y=220
TITLE_HEADER_X=500
COLUMN_HEADER_Y=120
HEADER_MENU_ARTIST_X=560
HEADER_MENU_ARTIST_Y=208
SIDEBAR_PLAYLIST_X=100
SIDEBAR_PLAYLIST_Y=226
SIDEBAR_PLAYLIST_DELETE_X=100
SIDEBAR_PLAYLIST_DELETE_Y=282
PLAYLIST_DELETE_CONFIRM_X=800
PLAYLIST_DELETE_CONFIRM_Y=475
SIDEBAR_QUEUE_X=80
SIDEBAR_QUEUE_Y=150
# Search is now a compact header toggle instead of a 300px entry. The end
# controls stay right-anchored; record every slot explicitly so future pointer
# recalibration cannot accidentally target the revealed second top bar.
PRIMARY_MENU_FROM_RIGHT=186
INFO_TOGGLE_FROM_RIGHT=222
SEARCH_TOGGLE_FROM_RIGHT=262
COMPACT_BUTTON_FROM_RIGHT=302
