#!/usr/bin/env python3
"""Generate palette-backed Android launcher resource wrappers."""

import argparse
import tomllib
from pathlib import Path


def generated_note():
    return "<!-- Generated by scripts/build-brand-assets.sh. Do not edit by hand. -->\n"


def colours(palette):
    body = "".join(
        f'    <color name="{name}">{value}</color>\n'
        for name, value in (
            ("reprise_teal", palette["reprise_teal"]),
            ("reprise_coral", palette["reprise_coral"]),
            ("reprise_plate", palette["reprise_plate"]),
        )
    )
    return '<?xml version="1.0" encoding="utf-8"?>\n' + generated_note() + f"<resources>\n{body}</resources>\n"


def adaptive_icon():
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        + generated_note()
        + '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        + '    <background android:drawable="@android:color/transparent"/>\n'
        + '    <foreground android:drawable="@drawable/ic_launcher_foreground"/>\n'
        + '    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>\n'
        + "</adaptive-icon>\n"
    )


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def build(palette_path, res_dir):
    palette = tomllib.loads(Path(palette_path).read_text(encoding="utf-8"))
    root = Path(res_dir)
    write(root / "values/colors.xml", colours(palette))
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        write(root / "mipmap-anydpi-v26" / name, adaptive_icon())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("palette")
    parser.add_argument("res_dir")
    args = parser.parse_args()
    build(args.palette, args.res_dir)


if __name__ == "__main__":
    main()
