#!/usr/bin/env python3
"""Render the maintained palette into the exact repeat-sign SVG sources."""

import argparse
import re
import tomllib
from pathlib import Path

PALETTE_KEYS = (
    "reprise_teal",
    "reprise_coral",
    "reprise_teal_light",
    "reprise_coral_light",
    "reprise_plate",
)
HEX = re.compile(r"#[0-9A-F]{6}")


def read_palette(path):
    palette = tomllib.loads(Path(path).read_text(encoding="utf-8"))
    if tuple(palette) != PALETTE_KEYS:
        raise SystemExit(
            f"palette keys must be exactly {', '.join(PALETTE_KEYS)}")
    invalid = [key for key, value in palette.items()
               if not isinstance(value, str) or not HEX.fullmatch(value)]
    if invalid:
        raise SystemExit(f"invalid uppercase six-digit palette values: {invalid}")
    if len(set(palette.values())) != len(palette):
        raise SystemExit("palette values must be unique")
    return palette


def mark_svg(small, large, explanation):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96" width="96" height="96">
  <!-- Generated from palette.toml. {explanation} -->
  <circle cx="30" cy="39" r="5.5" fill="{small}"/>
  <circle cx="30" cy="57" r="5.5" fill="{small}"/>
  <rect x="41" y="20" width="5" height="56" rx="1" fill="{small}"/>
  <rect x="52" y="20" width="15" height="56" rx="1.5" fill="{large}"/>
</svg>
'''


def mono_svg():
    return '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96" width="96" height="96"
     fill="currentColor">
  <!-- One geometry serves every theme-controlled surface so the symbolic
       and coloured repeat signs cannot drift into different marks. -->
  <circle cx="30" cy="39" r="5.5"/>
  <circle cx="30" cy="57" r="5.5"/>
  <rect x="41" y="20" width="5" height="56" rx="1"/>
  <rect x="52" y="20" width="15" height="56" rx="1.5"/>
</svg>
'''


def first_aid_symbolic_svg():
    return '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
     width="24" height="24" fill="currentColor">
  <!-- Palette-independent symbolic geometry generated by the brand pipeline. -->
  <path fill-rule="evenodd" d="M10.3 3h3.4a1.8 1.8 0 0 1 1.8 1.8v1.4A1.8 1.8 0 0 1 13.7 8h-3.4a1.8 1.8 0 0 1-1.8-1.8V4.8A1.8 1.8 0 0 1 10.3 3Zm.8 2h1.8a.6.6 0 0 1 .6.6v1.8a.6.6 0 0 1-.6.6h-1.8a.6.6 0 0 1-.6-.6V5.6a.6.6 0 0 1 .6-.6Z"/>
  <path fill-rule="evenodd" d="M5 6.5h14A2.5 2.5 0 0 1 21.5 9v9a2.5 2.5 0 0 1-2.5 2.5H5A2.5 2.5 0 0 1 2.5 18V9A2.5 2.5 0 0 1 5 6.5Zm.7 2h12.6a1.2 1.2 0 0 1 1.2 1.2v7.6a1.2 1.2 0 0 1-1.2 1.2H5.7a1.2 1.2 0 0 1-1.2-1.2V9.7a1.2 1.2 0 0 1 1.2-1.2Z"/>
  <rect x="11" y="10.25" width="2" height="6.5" rx=".4"/>
  <rect x="8.75" y="12.75" width="6.5" height="2" rx=".4"/>
</svg>
'''


def radio_symbolic_svg():
    return '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
     width="24" height="24" fill="currentColor">
  <!-- Palette-independent symbolic geometry generated by the brand pipeline. -->
  <path d="M7.464 9.386 17.964 3.886A1 1 0 0 0 17.036 2.114L6.536 7.614A1 1 0 0 0 7.464 9.386Z"/>
  <path fill-rule="evenodd" d="M5 7.5h14a3.5 3.5 0 0 1 3.5 3.5v7.5A3.5 3.5 0 0 1 19 22H5a3.5 3.5 0 0 1-3.5-3.5V11A3.5 3.5 0 0 1 5 7.5Zm0 2h14a1.5 1.5 0 0 1 1.5 1.5v7.5A1.5 1.5 0 0 1 19 20H5a1.5 1.5 0 0 1-1.5-1.5V11A1.5 1.5 0 0 1 5 9.5Z"/>
  <path fill-rule="evenodd" d="M8.5 10.75a4 4 0 1 1 0 8 4 4 0 0 1 0-8Zm0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4Z"/>
  <rect x="13.5" y="11.5" width="6.5" height="2" rx="1"/>
  <rect x="13.5" y="16" width="6.5" height="2" rx="1"/>
</svg>
'''


def stats_symbolic_svg():
    return '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"
     width="16" height="16" fill="currentColor">
  <!-- Palette-independent symbolic geometry generated by the brand pipeline.
       On the 16-unit grid, not the 24-unit grid the other symbolics use: this
       glyph is a one-unit axis and three bars, and the sidebar draws it at
       ICON_WIDTH = 16. A 24-unit drawing puts every one of those edges on a
       half pixel and the icon renders as grey mush — the same reason
       hinted_16_body exists for the mark. -->
  <rect x="2" y="2" width="1" height="12"/>
  <rect x="2" y="13" width="11" height="1"/>
  <rect x="4" y="9" width="2" height="4"/>
  <rect x="7" y="6" width="2" height="7"/>
  <rect x="10" y="3" width="2" height="10"/>
</svg>
'''


def hinted_16_body(small, large):
    """The repeat sign redrawn on the 16-unit grid, every edge on a whole line.

    The 96-unit geometry is the mark; this is the same sign at the one size
    where that geometry stops working. Scaled to 16px it renders four separate
    pixel groups of 20, 8, 2 and 2 pixels — nothing merges, but the dots are
    small enough that a detector treats them as noise and a viewer sees two
    specks. Here the dots are 3x3, the barlines are 1 and 3 pixels, and every
    gap is a whole pixel, so the 1:3 ratio that makes this a repeat sign rather
    than a rest survives at the smallest stage shipped.

    The dots are 3x3 rather than 2x2 because 2x2 leaves them at 4 pixels
    against a 3-pixel noise floor — countable, but one rounding decision away
    from vanishing. At 3x3 they are 9 pixels and read as dots beside a
    ten-pixel barline instead of as specks.

    Proportions run heavier than the 96-unit drawing on purpose: ink fills 64%
    of the viewBox width against 48% there, because thin features disappear
    at this size.
    """
    return (f'  <rect x="3" y="5" width="3" height="3" fill="{small}"/>\n'
            f'  <rect x="3" y="9" width="3" height="3" fill="{small}"/>\n'
            f'  <rect x="7" y="3" width="1" height="10" fill="{small}"/>\n'
            f'  <rect x="9" y="3" width="3" height="10" fill="{large}"/>\n')


def hinted_16_svg(small, large):
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">\n'
            '  <!-- Generated from palette.toml. The repeat sign on the 16-unit\n'
            '       grid, for the one raster stage where the 96-unit geometry\n'
            '       renders the dots as two specks. -->\n'
            + hinted_16_body(small, large) + '</svg>\n')


def hinted_16_mono_svg():
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"\n'
            '     fill="currentColor">\n'
            '  <!-- Single-colour form of the 16-unit drawing. -->\n'
            '  <rect x="3" y="5" width="3" height="3"/>\n'
            '  <rect x="3" y="9" width="3" height="3"/>\n'
            '  <rect x="7" y="3" width="1" height="10"/>\n'
            '  <rect x="9" y="3" width="3" height="10"/>\n'
            '</svg>\n')


def hinted_16_icon_svg(small, large):
    """Transparent desktop icon on the hinted 16-unit grid."""
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">\n'
            '  <!-- Generated from palette.toml. The desktop icon stays on a\n'
            '       transparent ground while preserving the hinted grid. -->\n'
            + hinted_16_body(small, large) + '</svg>\n')


def render(palette):
    # The colour split was decided at dock size against the alternative that
    # swapped the two: teal on the thick barline reads farther because the
    # large field carries the brighter colour (7.13:1 on the dark brand
    # neutral against coral's 4.42:1), and coral stays legible as the accent on
    # the dots and the thin barline. Only the chosen split is generated — a second one kept
    # "for comparison" is a second mark to keep in step, and the comparison is
    # over.
    return {
        "reprise-mark.svg": mark_svg(
            palette["reprise_coral"], palette["reprise_teal"],
            "Teal carries the thick barline so the\n"
            "       largest field holds the brighter colour; coral accents the dots\n"
            "       and the thin barline."),
        "reprise-mark-light.svg": mark_svg(
            palette["reprise_coral_light"], palette["reprise_teal_light"],
            "The deeper pair keeps that hierarchy\n"
            "       while clearing the graphical-object contrast floor on light ground."),
        "reprise-mark-mono.svg": mono_svg(),
        "io.github.marvinbaudach.Reprise-first-aid-symbolic.svg": first_aid_symbolic_svg(),
        "reprise-radio-symbolic.svg": radio_symbolic_svg(),
        "reprise-stats-symbolic.svg": stats_symbolic_svg(),
        "reprise-mark-16.svg": hinted_16_svg(
            palette["reprise_coral"], palette["reprise_teal"]),
        "reprise-mark-16-mono.svg": hinted_16_mono_svg(),
        "reprise-icon-16.svg": hinted_16_icon_svg(
            palette["reprise_coral"], palette["reprise_teal"]),
    }


def write_sources(palette_path, output_dir):
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    for name, text in render(read_palette(palette_path)).items():
        (output / name).write_text(text, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("palette")
    parser.add_argument("output_dir")
    args = parser.parse_args()
    write_sources(args.palette, args.output_dir)


if __name__ == "__main__":
    main()
