#!/usr/bin/env python3
"""Convert the app-icon plate to Android's full-bleed background layer.

Both solid and gradient SVG plates are accepted. A caller may replace the
literal solid fill with an Android resource reference so the palette remains
the only maintained source of brand colour values.
"""
import argparse
import re
from pathlib import Path

VIEWPORT = 108.0

_GRADIENT = re.compile(r"<linearGradient\b([^>]*)>(.*?)</linearGradient>", re.S)
_STOP = re.compile(r"<stop\b[^>]*offset=\"([^\"]+)\"[^>]*stop-color=\"([^\"]+)\"")
_RECT_FILL = re.compile(r"<rect\b[^>]*\bfill=\"([^\"]+)\"")


def _attr(text, name, default):
    match = re.search(rf'\b{name}="([^"]+)"', text)
    return float(match.group(1)) if match else default


def gradient(plate_text):
    """Start-, Endpunkt und Farbmarken des Verlaufs, in Viewport-Einheiten."""
    found = _GRADIENT.search(plate_text)
    if not found:
        raise SystemExit("Platte ohne linearGradient")
    head, body = found.group(1), found.group(2)
    stops = [(float(offset), colour) for offset, colour in _STOP.findall(body)]
    if len(stops) < 2:
        raise SystemExit(f"Verlauf mit {len(stops)} Farbmarke(n), mindestens 2 nötig")
    # objectBoundingBox ist der Vorgabewert von SVG und der Fall, den die
    # Platte benutzt: die Koordinaten sind Anteile der Fläche.
    units = re.search(r'gradientUnits="([^"]+)"', head)
    if units and units.group(1) != "objectBoundingBox":
        raise SystemExit(f"gradientUnits={units.group(1)} wird nicht abgebildet")
    box = [_attr(head, "x1", 0.0), _attr(head, "y1", 0.0),
           _attr(head, "x2", 1.0), _attr(head, "y2", 0.0)]
    return [value * VIEWPORT for value in box], stops


def solid_fill(plate_text):
    found = _RECT_FILL.search(plate_text)
    if not found:
        raise SystemExit("plate has neither a solid rect fill nor a linearGradient")
    fill = found.group(1)
    if fill.startswith("url("):
        return None
    return fill


def build(plate_text, colour_ref=None):
    fill = solid_fill(plate_text)
    if fill is not None:
        fill = colour_ref or fill
        return (
            '<?xml version="1.0" encoding="utf-8"?>\n'
            "<!-- Generated by scripts/build-brand-assets.sh."
            " Do not edit by hand. -->\n"
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{VIEWPORT:g}dp"\n'
            f'    android:height="{VIEWPORT:g}dp"\n'
            f'    android:viewportWidth="{VIEWPORT:g}"\n'
            f'    android:viewportHeight="{VIEWPORT:g}">\n'
            f'    <path android:fillColor="{fill}" '
            f'android:pathData="M0,0h{VIEWPORT:g}v{VIEWPORT:g}h-{VIEWPORT:g}z"/>\n'
            "</vector>\n"
        )

    if colour_ref:
        raise SystemExit("--colour-ref can only replace a solid plate fill")
    (x1, y1, x2, y2), stops = gradient(plate_text)
    items = "".join(
        f'                    <item android:offset="{offset:g}" '
        f'android:color="{colour}"/>\n'
        for offset, colour in stops)
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by scripts/build-brand-assets.sh."
        " Do not edit by hand. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    xmlns:aapt="http://schemas.android.com/aapt"\n'
        f'    android:width="{VIEWPORT:g}dp"\n'
        f'    android:height="{VIEWPORT:g}dp"\n'
        f'    android:viewportWidth="{VIEWPORT:g}"\n'
        f'    android:viewportHeight="{VIEWPORT:g}">\n'
        f'    <path android:pathData="M0,0h{VIEWPORT:g}v{VIEWPORT:g}h-{VIEWPORT:g}z">\n'
        '        <aapt:attr name="android:fillColor">\n'
        '            <gradient android:type="linear"\n'
        f'                android:startX="{x1:g}" android:startY="{y1:g}"\n'
        f'                android:endX="{x2:g}" android:endY="{y2:g}">\n'
        f"{items}"
        "            </gradient>\n"
        "        </aapt:attr>\n"
        "    </path>\n"
        "</vector>\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("plate")
    parser.add_argument("destination")
    parser.add_argument("--colour-ref",
                        help="replace a solid SVG fill with an Android colour resource")
    args = parser.parse_args()
    Path(args.destination).write_text(
        build(Path(args.plate).read_text(encoding="utf-8"), args.colour_ref),
        encoding="utf-8")


if __name__ == "__main__":
    main()
